---
name: Check
"on": [push]

env:
  RUBY_VERSION: 3.1.2
  SHELL: "/bin/bash"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          bundle config set with 'test'
          bundle install
      - name: Check code
        run: bundle exec rubocop

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          bundle config set with 'test'
          bundle install
      - name: RSpec
        run: bundle exec rspec
