---
name: Release Gem
"on": [push]

env:
  RUBY_VERSION: 2.7

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: bundle
      - name: Check code
        run: bundle exec rubocop

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: bundle install --with test
      - name: RSpec
        run: bundle exec rspec

  build:
    needs: [unit, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Version Gem
      #   run: bundle exec bump pre --tag
      - name: Build and publish gem
        uses: damacus/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: damacus
