---
name: Release Gem
"on":
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Version Gem
        run: bundle exec bump patch --tag
      - name: Build and publish gem
        uses: damacus/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: damacus
